name: Manny Poole
permalink: :year/:month/:day/:title
baseurl: ""

# Your blog's start year and this year, showed in the footer left
# start is optional
start: 2022
#now: 2019
 
# Social links showed in the footer
# You just need modify the nickname of github and twitter
link:
  #email : yourname@gmail.com
  github : mannypoole
  twitter : mannypoole

# Links in the navigation, you can modify both link name and link url
nav:
   Home: "/"
   Logs: "/entries"

   
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed
